# Generated by Django 3.1.5 on 2021-01-19 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0023_auto_20200711_0629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, choices=[('Not Specified', 'Not Specified'), ('Consumer Goods', 'Consumer Goods'), ('Household Appliances', 'Household Appliances'), ('Food and Beverage', 'Food and Beverage'), ('Automobiles', 'Automobiles'), ('Musical Instruments', 'Musical Instruments'), ('Sporting Goods', 'Sporting Goods'), ('Other', 'Other')], default='test', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
